
UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = 3
WHERE [CODIGO DO PRODUTO] = '1040107';

UPDATE [TABELA DE VENDEDORES]
SET [COMISSAO] = 0.11
WHERE [MATRICULA] = '00235';

UPDATE [TABELA DE VENDEDORES]
SET [NOME] = 'Cláudia Morais Sousa'
WHERE [MATRICULA] = '00236';

UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = 17.50, [EMBALAGEM] = 'Copo'
WHERE [CODIGO DO PRODUTO] = '1000889';


SELECT * FROM [TABELA DE PRODUTOS];
SELECT * FROM [TABELA DE CLIENTES];
SELECT * FROM [TABELA DE VENDEDORES];
