----Função de concatenação de endereços

CREATE FUNCTION Enderecocompleto
(@ENDERECO VARCHAR(100),
@BAIRRO VARCHAR(50),
@CIDADE VARCHAR(50),
@ESTADO VARCHAR(2),
@CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN
    DECLARE @ENDERECO_COMPLETO VARCHAR(250)
    SET @ENDERECO_COMPLETO = @ENDERECO + '-' + 
    @BAIRRO + '-' + @CIDADE + '-' + @ESTADO + '-' + @CEP
    RETURN @ENDERECO_COMPLETO
END
---- seleciona a funçao concactnaçao
SELECT CPF, [dbo].[Enderecocompleto]([ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP) AS ENDERECO_COMPLETO FROM [TABELA DE CLIENTES]

-----
CREATE FUNCTION Enderecocompleto
(@ENDERECO VARCHAR(100),
@BAIRRO VARCHAR(50),
@CIDADE VARCHAR(50),
@ESTADO VARCHAR(2),
@CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN

    DECLARE @ENDERECO_COMPLETO VARCHAR(250)
    SET @ENDERECO_COMPLETO = @ENDERECO + ' ' + 
    @BAIRRO + ' ' + @CIDADE + ' ' + @ESTADO + ', CEP ' + @CEP
    RETURN @ENDERECO_COMPLETO
END
---- Alteraçao para tirar os espaços e acrescentar CEP;
ALTER FUNCTION Enderecocompleto
(@ENDERECO VARCHAR(100),
@BAIRRO VARCHAR(50),
@CIDADE VARCHAR(50),
@ESTADO VARCHAR(2),
@CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN

    DECLARE @ENDERECO_COMPLETO VARCHAR(250)
    SET @ENDERECO_COMPLETO = @ENDERECO + ' ' + 
    @BAIRRO + ' ' + @CIDADE + ' ' + @ESTADO + ', CEP ' + @CEP
    RETURN @ENDERECO_COMPLETO
END
---- seleciona a nova funçao concactnaçao
SELECT CPF, [dbo].[Enderecocompleto]([ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP) AS ENDERECO_COMPLETO FROM [TABELA DE CLIENTES]
----
