
SELEC * FROM [TABELA DE CLIENTES];

SELECT BAIRRO, SUM([LIMITE DE CRÉDITO]) FROM [TABELA CLIENTES] GROUP BY BAIRRO
--
WHERE BAIRRO = 'Água Santa'
SELECT SUM([LIMITE DE CRÉDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = 'Água Santa'
---// Código omitido

SET @LIMITE_MÁXIMO = 50000;
SET @BAIRRO = [Água Santa];
-----// Código omitido

SELECT @LIMITE_ATUAL = SUM([LIMITE DE CRÉDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO;

DECLARE @LIMITE_MAXIMO FLOAT;
DECLARE @LIMITE_ATUAL FLOAT;
DECLARE @BAIRRO VARCHAR(20);
---
SET @LIMITE_MÁXIMO = 50000;
SET @BAIRRO = [Água Santa];
SELECT @LIMITE_ATUAL = SUM([LIMITE DE CRÉDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO;
IF @LIMITE_MAXIMO <= @LIMITE ATUAL
    PRINT 'VALOR ESTOUROU';
ELSE
    PRINT 'VALOR NÃO ESTOUROU';