
--Data atual;
SELECT GETDATE()
--Dia da semana de hoje;
SELECT DATENAME (WEEKDAY, GETDATE())
--a daqui 5 dias.
SELECT DATEADD(DAY, 5, GETDATE())
--Dia de hoje e de 5 dias a frente;
SELECT GETDATE(), DATEADD(DAY, 5, GETDATE())
--dia da semana daqui 5 dias
SELECT DATENAME (WEEKDAY, DATEADD(DAY, 5, GETDATE());
----***Data daqui 9 dias***---
DECLARE @DIA_SEMANA VARCHAR(20);
DECLARE @NUMERO_DIAS INT;

SET @NUMERO_DIAS = 9;
SET @DIA_SEMANA = DATENAME (WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()));
PRINT @DIA_SEMANA;
--------------------
// Código omitido

SET @NUMERO_DIAS = 15;
--------------------
IF @DIA_SEMANA = 'Domingo ' OR @DIA_SEMANA = 'Sábado'
    PRINT 'Este dia é fim de semana';
ELSE
    PRINT 'Este dia é dia de semana';
	-----------------------Daqui 15 dias
	DECLARE @DIA_SEMANA VARCHAR(20);
DECLARE @NUMERO_DIAS INT;

SET @NUMERO_DIAS = 15;
SET @DIA_SEMANA = DATENAME (WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()));
PRINT @DIA_SEMANA;

IF @DIA_SEMANA = 'Domingo ' OR @DIA_SEMANA = 'Sábado'
    PRINT 'Este dia é fim de semana';
ELSE
    PRINT 'Este dia é dia de semana';
	-----atualiza o campo IDADE da TABELA DE CLIENTES com a idade atual,-------------------------
	DECLARE @CPF VARCHAR(15);
   DECLARE @DATA_NASCIMENTO DATE;
   DECLARE @IDADE INT;

   SET @CPF = '1471156710';
   SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
   SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());
   UPDATE [TABELA DE CLIENTES] SET IDADE = @IDADE WHERE CPF = @CPF;
   --- idade atual
DECLARE @CPF VARCHAR(15);
DECLARE @IDADE_TABELA INT;
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @IDADE INT;

SET @CPF = '1471156710';
SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE_TABELA = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());
IF @IDADE_TABELA <> @IDADE UPDATE [TABELA DE CLIENTES] SET IDADE = @IDADE WHERE CPF = @CPF;