--
SELECT NOME FROM [TABELA DE CLIENTES]
---mostrar a posiçao do primeiro espaçp
SELECT NOME, CHARINDEX(' ', NOME) FROM [TABELA DE CLIENTES]
---mostrar a posiçao do primeiro espaço e o primeiro nome
SELECT NOME, CHARINDEX(' ', NOME), SUBSTRING(NOME, 1, CHARINDEX(' ', NOME)) FROM [TABELA DE CLIENTES]
SELECT NOME, CHARINDEX(' ', NOME), SUBSTRING(NOME, 1, CHARINDEX(' ', NOME) - 1) FROM [TABELA DE CLIENTES]
----O primeiro nome do cliente César Teixeira, cujo CPF é 2600586709, corresponde a César
DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

SET @CPF = '2600586709';

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT 'O primeiro nome do cliente ' + @NOME + ', cujo CPF é ' + @CPF + ', corresponde a ' + SUBSTRING(@NOME, 1, CHARINDEX(' ', @NOME) - 1);
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;
---- O primeiro nome do cliente Érica Carvalho, cujo CPF é 1471156710, corresponde a Érica
DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

SET @CPF = '1471156710';

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT 'O primeiro nome do cliente ' + @NOME + ', cujo CPF é ' + @CPF + ', corresponde a ' + SUBSTRING(@NOME, 1, CHARINDEX(' ', @NOME) - 1);
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;
---------------------------Exibição direta do resultado de uma função.
DECLARE @CPF VARCHAR(15);
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @IDADE INT;

SET @CPF = '1471156710';
SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
PRINT DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());