------------- Atribuir esse Nº CPF a variavel @CPF
DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;
SET @CPF = '19290992743';
SELECT * FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
--------------Selecionar esse Nome, DataDeNascimento,Idade  a variavel @IDADE,@NOME,@DATA_NASCIMENTO.
DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

SET @CPF = '19290992743';

SELECT NOME, [DATA DE NASCIMENTO], IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
--------------Atribuir esse Nome, DataDeNascimento,Idade  a variavel @IDADE,@NOME,@DATA_NASCIMENTO.------------------------------------
DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

SET @CPF = '19290992743';

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
----------------------------------------------------------------------------------------------------
DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

SET @CPF = '19290992743';

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT @NOME;
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;
--------Retorno os dados de Fernando Cavalcante------------------------------------------------------------------
DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

SET @CPF = '19290992743';

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT @NOME;
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;
-------Retorna os dados do César--------------------------------------------------------------------------------
DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

SET @CPF = '2600586709';

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT @NOME;
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;
-----------------Atribuir a ela o número de notas fiscais do dia 01/01/2017---------------------------------------------------------
DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = '20170101'
PRINT @NUMNOTAS