--
CREATE TABLE #TABELA01 (ID VARCHAR(10), NOME VARCHAR(30));
CREATE TABLE ##TABELA02 (ID VARCHAR(10), NOME VARCHAR(30));

INSERT INTO #TABELA01 VALUES ('1', 'JOÃO');
INSERT INTO #TABELA01 VALUES ('2', 'KATIA');
INSERT INTO ##TABELA02 VALUES ('1', 'JOSE');
INSERT INTO ##TABELA02 VALUES ('2', 'ANA');
INSERT INTO ##TABELA02 VALUES('3', 'JORGE');

SELECT * FROM #TABELA01;
SELECT * FROM ##TABELA02;

----
DECLARE @NUMERO_ANTERIOR2 INT;
DECLARE @NUMERO_ANTERIOR1 INT;
DECLARE @NUMERO_ATUAL INT;
DECLARE @SEQUENCIA INT;
DECLARE @CONTADOR_SEQUENCIA INT;
DECLARE @TABELA TABLE (SEQUENCIA INT, VALOR INT);

SET @SEQUENCIA = 44;
SET @CONTADOR_SEQUENCIA = 3;

SET @NUMERO_ANTERIOR2 = 0;
SET @NUMERO_ANTERIOR1 = 1;
INSERT INTO @TABELA VALUES (1,0);
INSERT INTO @TABELA VALUES (2,1);
WHILE @CONTADOR_SEQUENCIA <= @SEQUENCIA
BEGIN
   SET @NUMERO_ATUAL = @NUMERO_ANTERIOR2 + @NUMERO_ANTERIOR1;
   INSERT INTO @TABELA VALUES (@CONTADOR_SEQUENCIA,@NUMERO_ATUAL);
   SET  @NUMERO_ANTERIOR2 = @NUMERO_ANTERIOR1;
   SET @NUMERO_ANTERIOR1 = @NUMERO_ATUAL;
   SET @CONTADOR_SEQUENCIA = @CONTADOR_SEQUENCIA + 1;
END;
SELECT * FROM @TABELA;
-----
DECLARE @NUMERO_INICIAL_SEQUENCIA INT, @NUMERO_FINAL_SEQUENCIA INT;
DECLARE @TESTE_NOTA_FISCAL INT;
DECLARE @TABELA_DE_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(20));

SET @NUMERO_INICIAL_SEQUENCIA = 1;
SET @NUMERO_FINAL_SEQUENCIA = 200;

WHILE @NUMERO_INICIAL_SEQUENCIA <= @NUMERO_FINAL_SEQUENCIA
BEGIN
        SELECT @TESTE_NOTA_FISCAL = COUNT(*) FROM [NOTAS FISCAIS] WHERE 
        NUMERO = @NUMERO_INICIAL_SEQUENCIA;
        IF @TESTE_NOTA_FISCAL = 1
             INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
             VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É NOTA FISCAL');
        ELSE
             INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
             VALUES (@NUMERO_INICIAL_SEQUENCIA, 'NÃO É NOTA FISCAL');
        SET @NUMERO_INICIAL_SEQUENCIA = @NUMERO_INICIAL_SEQUENCIA + 1;
END;
--- @ Visualiaza somente qdo for executado o arquivo
SELECT * FROM @TABELA_DE_NUMEROS;
---# Visualiaza somente em qdo o servidor nao for reiniciado
SELECT * FROM #TABELA_DE_NUMEROS;