--Retorna toda a tabela
SELECT * FROM TABELA_DE_PRODUTOS WHERE 1=1;

SELECT * FROM TABELA_DE_PRODUTOS;

--Nao iria retorna nada
SELECT * FROM TABELA_DE_PRODUTOS WHERE 1=0;
--Ira retorna somente o codigo
SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '290478';
--Ira retorna somente o somente os de sabores laranja.
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja';
SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'PET';
SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'pet';
------------Filtros quantitativos.
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE > 20;
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 20;
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 18;
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <> 18;
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '1995-11-14';
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO <= '1995-11-14';
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'Lapa';
---------- Expressões lógicas
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND TAMANHO ='470 ml';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR TAMANHO ='470 ml';
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' AND TAMANHO='470 ml');
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' OR TAMANHO='470 ml');
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR SABOR = 'Laranja' OR SABOR = 'Melancia';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR in ('Manga', 'Laranja', 'Melancia') AND TAMANHO = '1 Litro';
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE in ('Rio de Janeiro', 'Sao Paulo');
--As duas trazem os mesmo resultados
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE in ('Rio de Janeiro', 'Sao Paulo') AND (IDADE >= 20 AND IDADE <= 25);
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE in ('Rio de Janeiro', 'Sao Paulo') AND (IDADE BETWEEN 20 AND 25);
--
SELECT * FROM CLIENTE WHERE LIKE '%TESTE%';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Lima/Limão', 'Morango/Limão');
SELECT  * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limão');
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Maca';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'Morango%';
SELECT * FROM TABELA_DE_PRODUTOS WHERE (*SABOR LIKE 'Morango%') AND (EMBALAGEM = 'PET');
SELECT * FROM TABELA_DE_CLIENTES WHERE NOME LIKE '%Silva%';