-- Clientes que realizaram compras
SELECT
TC.CPF AS CPF_DO_CADASTRO,
TC.NOME AS NOME_DO_CLIENTE,
NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF;
--Clientes que realizaram compras sem duplicidade
SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO,
TC.NOME AS NOME_DO_CLIENTE,
NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF;

-- inclusao de cliente;
INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2,
BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, GENERO,
LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
VALUES ('23412632331', 'Juliana Silva', 'Rua Tramandaí', ' ', 'Bangu', 'Rio de
Janeiro', 'RJ', '23400000', '1989-02-04', 33, 'F', '180000', '24500', 0);
--Clientes que nao fizeram nenhuma compra.
SELECT DISTINCT 
TC.CPF AS CPF_DO_CADASTRO, TC.NOME AS NOME_DO_CLIENTE, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
LEFT JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF 
WHERE NF.CPF IS NULL
----
SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
-- Vendedor Bairro
SELECT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR 
FROM TABELA_DE_CLIENTES TC 
INNER JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;
-- Vendedor e comprador por Bairro
SELECT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
INNER JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;
--
SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
INNER JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;
--vendedor que nao vez comprar
SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
--clientes que moram ou têm sede em determinados bairros que não possuem vendedores
SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
LEFT JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO 
WHERE TV.NOME IS NULL;
--
SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
FULL JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
RIGHT JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;