
CREATE TABLE TAB_IDENTITY (
    ID INT IDENTITY(1,1) NOT NULL, 
    DESCRITOR VARCHAR (20) NULL
);
---
SELECT * FROM TAB_IDENTITY;
SELECT * FROM TAB_IDENTITY2;
SELECT * FROM TB_PADRAO;
---
INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE X');
INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE Y');
INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE Z');
INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE W');
INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE A');
INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE B');
INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE C');
---
DELETE FROM TAB_IDENTITY WHERE ID = 6;
---
DELETE FROM TAB_IDENTITY WHERE ID = 1;

DELETE FROM TB_PADRAO;
---
CREATE TABLE TAB_IDENTITY2 (
    ID INT IDENTITY(100,5) NOT NULL, 
    DESCRITOR VARCHAR (20) NULL
);
---
INSERT INTO TAB_IDENTITY2 (DESCRITOR) 
VALUES ('CLIENTE Y');

INSERT INTO TAB_IDENTITY2 (DESCRITOR) 
VALUES ('CLIENTE Z');
--
CREATE TABLE TB_PADRAO (
    ID INT IDENTITY(1,1) NOT NULL, 
    DESCRITOR VARCHAR(20) NULL, 
    ENDERECO VARCHAR(20) NULL, 
    CIDADE VARCHAR(20) DEFAULT 'Rio de Janeiro', 
    DATA_CRIACAO DATE DEFAULT GETDATE()
);
---
INSERT INTO TB_PADRAO 
    (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO) 
VALUES
    ('CLIENTE X', 'RUA PROJETADA A', 'SÃO PAULO', '2018-04-30');
---
SELECT * FROM TB_PADRAO;
---
INSERT INTO TB_PADRAO (DESCRITOR) 
VALUES ('CLIENTE Y');